config/routes.rb
Rails.application.routes.draw do
  get 'gyms/new'

  get 'gyms/create'

  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  root 'static_pages#home'
  get 'home' => 'static_pages#home'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'help' => 'static_pages#help'
  get 'climber_signup' => 'climbers#new'
  get 'gym_signup' => 'gym#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :gyms do
    resources :routes
  end
  resources :climbers do
    member do
      get :projects
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :projects, only: [:create, :destroy] do
    member do
      put :complete
    end
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end

  def help
  end
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<h1>About</h1>
<p>
  My name is Jacob Swartzentruber and I am currently learning how to design
  web applications.  I have been an avid climber for the past few years and
  decided I needed an application to track routes and workouts.
</p>
<p>
  You can check out the progress I have made teaching myself web application
  development in <a href="http://jacobswartzentruber.github.io/">my blog and portfolio here</a>.
</p>

app/views/static_pages/contact.html.erb
<h1>Contact</h1>
<p>This web application was designed by Jacob Swartzentruber</p>
<p>
  You can check out the progress I have made teaching myself web application
  development in <a href="http://jacobswartzentruber.github.io/">my blog and portfolio here</a>.
</p>

app/views/static_pages/help.html.erb
<h1>Help</h1>
<p>
  If you have any questions or comments, please reach out to me through <a href="http://jacobswartzentruber.github.io/">my development
  blog and portfolio</a>.
</p>

app/views/static_pages/home.html.erb
<!-- Carousel ================================================== -->
<div id="myCarousel" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <%= image_tag("first_slide.png", alt: "first_slide") %>
      <div class="container">
        <div class="carousel-caption">
          <h1>Welcome to ClimbON</h1>
          <p>ClimbON is an application that allows you to track your workout progress and
             catalogue the routes you have climbed</p>
          <%= link_to "Sign up today", new_climber_path, class: "btn btn-lg btn-primary" %>
        </div>
      </div>
    </div>
    <div class="item">
      <%= image_tag("second_slide.png", alt: "second_slide") %>
      <div class="container">
        <div class="carousel-caption">
          <h1>Gym Owner?</h1>
          <p>Create a gym profile to showcase your routes and track
             their popularity.  Reach out to the climbing community
             by posting upcoming events</p>
          <%= link_to "Create Gym Profile", new_gym_path, class: "btn btn-lg btn-primary" %>
        </div>
      </div>
    </div>
    <div class="item">
      <%= image_tag("third_slide.png", alt: "third_slide") %>
      <div class="container">
        <div class="carousel-caption">
          <h1>Interested in following development?</h1>
          <p>Visit the development blog to keep up to date with the newest
             improvements and additions to ClimbON!</p>
          <%= link_to "Learn More", "http://jacobswartzentruber.github.io/", class: "btn btn-lg btn-primary" %>
        </div>
      </div>
    </div>
  </div>
  <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div><!-- /.carousel -->