config/routes.rb
Rails.application.routes.draw do
  get 'gyms/new'

  get 'gyms/create'

  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  root 'static_pages#home'
  get 'home' => 'static_pages#home'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'help' => 'static_pages#help'
  get 'climber_signup' => 'climbers#new'
  get 'gym_signup' => 'gym#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :gyms do
    resources :routes
  end
  resources :climbers do
    member do
      get :projects
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :projects, only: [:create, :destroy] do
    member do
      put :complete
    end
  end

end

app/models/climber.rb
class Climber < ActiveRecord::Base
  has_one :user, as: :profile, dependent: :destroy, inverse_of: :profile
  accepts_nested_attributes_for :user
  has_many :projects, dependent: :destroy
  has_many :routes, through: :projects do 
    def completed
      where("projects.completed = (?)", true)
    end
    def uncompleted
      where("projects.completed = (?)", false)
    end
  end

  #Add a project
  def add_project(project_route)
  	self.projects.create(route_id: project_route.id)
  end

  #Remove a project
  def remove_project(project_route)
  	self.projects.find_by(route_id: project_route.id).destroy
  end

  #Returns true if climber is working on this project
  def working_on?(project_route)
  	self.routes.include?(project_route)
  end

  #Complete a project
  def completed_project?(project_route)
    self.projects.find_by(route_id: project_route.id).completed
  end

end

app/controllers/climbers_controller.rb
class ClimbersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: :destroy
  
  def index
    @climbers = Climber.paginate(page: params[:page])
  end
  
  def show
    @climber = Climber.find(params[:id])
  end
  
  def new
    @climber = Climber.new
    @climber.build_user
  end

  def create
    @climber = Climber.new(climber_params)
    if @climber.save
      @climber.user.send_activation_email
      flash[:info] = "Please check your email to activate your account."
      redirect_to root_url
    else
      render 'new'
    end
  end
  
  def edit
    @climber = Climber.find(params[:id])
  end
  
  def update
    @climber = Climber.find(params[:id])
    if @climber.update_attributes(climber_params)
      flash[:success] = "Profile successfully updated"
      redirect_to @climber
    else
      render 'edit'
    end
  end
  
  def destroy
    Climber.find(params[:id]).destroy 
    redirect_to climbers_path
  end
  
  private
  
    def climber_params
      params.require(:climber).permit(user_attributes: [:id, :name, :email, :password, :password_confirmation])
    end
  
    def correct_user
      @climber = Climber.find(params[:id])
      redirect_to root_url unless current_user?(@climber.user)
    end
    
    def admin_user
      redirect_to root_url unless current_user.admin?
    end
end

app/helpers/climbers_helper.rb
module ClimbersHelper
end

app/views/climbers/_climber.html.erb
<p>
  <%= link_to climber.user.name, climber_path(climber) %>
  <% if current_user.admin? && !current_user?(climber.user) %>
    <%= link_to "delete", climber, method: :delete,
                                data: { confirm: "You sure?" } %>
  <% end %>
</p>

app/views/climbers/edit.html.erb
<h1>Edit your Account</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@climber) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      
      <%= f.fields_for :user do |u| %>
        <%= u.label :name %>
        <%= u.text_field :name, class: "form-control" %>
        
        <%= u.label :email %>
        <%= u.email_field :email, class: "form-control" %>
        
        <%= u.label :password %>
        <%= u.password_field :password, class: "form-control" %>
        
        <%= u.label :password_confirmation %>
        <%= u.password_field :password_confirmation, class: "form-control" %>
      <% end %>
      
      <%= f.submit "Save Changes", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/climbers/index.html.erb
<h1>Index of Climbers</h1>

<%= will_paginate %>

<%= render @climbers %>

<%= will_paginate %>

app/views/climbers/new.html.erb
<h1>Climber Signup</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@climber) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      
      <%= f.fields_for :user do |builder| %>
        <%= builder.label :name %>
        <%= builder.text_field :name, class: "form-control" %>
        
        <%= builder.label :email %>
        <%= builder.email_field :email, class: "form-control" %>
        
        <%= builder.label :password %>
        <%= builder.password_field :password, class: "form-control" %>
        
        <%= builder.label :password_confirmation %>
        <%= builder.password_field :password_confirmation, class: "form-control" %>
        
        <% end %>
        <p>
          Are you the owner of a gym?
          <%= link_to "Create your gym profile here", new_gym_path %>
        </p>
      <%= f.submit "Create My Account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/climbers/show.html.erb
<h1><%= @climber.user.name %>'s Profile</h1>
<div class="row">
  <section class="col-md-6">
    <h2> Projects </h2>
    <div class="routes">
    	<%= render @climber.routes.uncompleted %>
  	</div>
  </section>
  <section class="col-md-6">
    <h2> Completed Routes </h2>
    <div class="routes">
    	<%= render @climber.routes.completed %>
  	</div>
  </section>
</div>