config/routes.rb
Rails.application.routes.draw do
  get 'gyms/new'

  get 'gyms/create'

  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  root 'static_pages#home'
  get 'home' => 'static_pages#home'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'help' => 'static_pages#help'
  get 'climber_signup' => 'climbers#new'
  get 'gym_signup' => 'gym#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :gyms do
    resources :routes
  end
  resources :climbers do
    member do
      get :projects
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :projects, only: [:create, :destroy] do
    member do
      put :complete
    end
  end

end

app/models/route.rb
class Route < ActiveRecord::Base
  belongs_to :gym
  has_many :projects, dependent: :destroy
  has_many :climbers, through: :projects
  
  validates_presence_of :gym_id
  validates :color, presence: true
  validates :difficulty, presence: true
  validates :description, length: {maximum: 140}


  #Returns status of project
  def project_status(user, logged_in)
  	if logged_in && user.profile_type == "Climber"
	    if self.climbers.include?(user.profile)
	      if self.projects.find_by(climber_id: user.profile.id).completed
	        return "completed"
	      else
	        return "uncompleted"
	      end
	    end
	    return "not-project"
	  end
  end

end

app/controllers/routes_controller.rb
class RoutesController < ApplicationController
  
  def new
    @gym = Gym.find(params[:gym_id])
    @route = @gym.routes.build()
  end
  
  def create
    @gym = Gym.find(params[:gym_id])
    @route = @gym.routes.build(route_params)
    if @route.save
      flash[:success] = "Route saved"
      redirect_to @gym
    else
      render 'new'
    end
  end
  
  def index
    @gym = Gym.find(params[:id])
    @routes = @gym.routes
  end
  
  def show
    @gym = Gym.find(params[:gym_id])
    @route = @gym.routes.find(params[:id])
  end
  
  private
    
    def route_params
      params.require(:route).permit(:name, :color, :difficulty, :description)
    end
end

app/helpers/routes_helper.rb
module RoutesHelper
end

app/views/routes/_route.html.erb
<div id="route-<%= route.id %>" class="route <%=route.project_status(current_user, logged_in?)%>">
  <div class="image">
    <%= image_tag("400x250.gif", size:"200x125" ) %>
  </div>
  <div class="content">
    <div class="title">
      <%= link_to "\""+route.name+"\"", gym_route_path(route.gym, route) %> - 
      <%= route.difficulty %>
    </div>
    <div class="description">
      <%= route.description %>
    </div>
    <div class="timestamp">
      Created on <%= route.created_at.strftime("%A %B %d, %Y") %>
    </div>
  </div>
  
  <div class="status">
    <% if logged_in? && current_user.profile_type == "Climber" %>
      <% if current_profile.working_on?(route) %>
        <% if !current_profile.completed_project?(route) %>
          <%= link_to "Remove from my projects", project_path(current_profile.projects.find_by(route_id: route.id)), method: :delete,
                                    class: "btn btn-default btn-sm" %>
          <%= link_to "Completed?", complete_project_path(current_profile.projects.find_by(route_id: route.id)), method: :put,
                                    class: "btn btn-primary btn-sm" %>
        <% end %>
      <% else %>
        <%= link_to "Add to my projects", projects_path(climber_id: current_profile.id, route_id: route.id), method: :post,
                                    class: "btn btn-primary btn-sm" %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/routes/new.html.erb
<h1>Create a new Route</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for([@gym, @gym.routes.build]) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>
      
      <div class="row">
        <div class="col-sm-6">
          <%= f.label :difficulty %>
          <%= f.text_field :difficulty, class: "form-control" %>
        </div>
        <div class="col-sm-6">
          <%= f.label :color %>
          <%= f.color_field :color, class: "form-control" %>
        </div>
      </div>
      
      <%= f.label :description %>
      <%= f.text_area :description, placeholder: "Any notes to share?", class: "form-control" %>

      <%= f.submit "Create Route", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/routes/show.html.erb
<h1>"<%= @route.name %>"</h1>

<p>Difficulty: <%= @route.difficulty %> <%= @route.color %></p>

<p>Date Route Set: <%= @route.created_at.strftime("%A %B %d, %Y") %></p>

<p>Description of route: <%= @route.description %></p>