config/routes.rb
Rails.application.routes.draw do
  get 'gyms/new'

  get 'gyms/create'

  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  root 'static_pages#home'
  get 'home' => 'static_pages#home'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'help' => 'static_pages#help'
  get 'climber_signup' => 'climbers#new'
  get 'gym_signup' => 'gym#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :gyms do
    resources :routes
  end
  resources :climbers do
    member do
      get :projects
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :projects, only: [:create, :destroy] do
    member do
      put :complete
    end
  end

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Climbing Application by Jacob Swartzentruber
  </small>
  <nav>
    <ul class="pull-right">
      <li><%= link_to "Contact", contact_url %></li>
      <li><%= link_to "About", about_url %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <%= link_to "ClimbON", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", home_path %></li>
        <li><%= link_to "Help", help_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Climbers", climbers_path %></li>
          <li><%= link_to "Gyms", gyms_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%=current_user.name%> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user.profile %></li>
              <% if current_user.profile_type == "Gym" %>
                <li><%= link_to "Settings", edit_gym_path(current_user.profile) %></li>
              <% elsif current_user.profile_type == "Climber" %>
                <li><%= link_to "Settings", edit_climber_path(current_user.profile) %></li>
              <% end %>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log In", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ClimbingApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>
<body>
  <%= render 'layouts/header' %>

  <div class="container">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
  </div>
  
  <%= render 'layouts/footer' %>
  <%= debug(params) if Rails.env.development? %>
</body>
</html>